### ISSUE TITLE
README

### ISSUE THREAD

**Issue by choisy** [thinhong/cpp_training#1]
Can you please write a README that explains what I should do on my computer in order to run your programme?

**Comment by thinhong** [comment]
Sure, I will write it soon

**Comment by thinhong** [comment]
I have written the steps to run our program, please see the README here: https://github.com/thinhong/cpp_training/blob/main/README.md

**Comment by choisy** [comment]
I got the following error when I run the executable:
```
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::parse_error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```
I seems to be related to the json file. Would you mind checking that?

**Comment by choisy** [comment]
I thing this issue is now fully addressed, I'm thus closing it. Don't forget to close the issues once you've addressed them so that you can keep a clean list of issues. Good to close them with comment so that every one can get informed.
