### ISSUE TITLE
Enter full path to input file

### ISSUE THREAD

**Issue by choisy** [thinhong/cpp_training#2]
Can we use relative paths or should it be absolute paths only?

**Comment by choisy** [comment]
It seems that we can use relative path. So, in the following message:
```
Enter full path to input file (ex: /home/Documents/config.json): 
```
good to remove the word "full" because it does not need to be full.
Don't forget to close the issue once you've addressed it.

**Comment by thinhong** [comment]
Thank Marc, I see all of your responses, I will address them and then close the issues
