### ISSUE TITLE
Set path to the folder you want to save output file

### ISSUE THREAD

**Issue by choisy** [thinhong/cpp_training#4]
Questions:

1. does it need to be an absolute path or is a relative path OK?
2. does the path need to exist or will it be created if it does not?
3. what happens if there are already simulations outputs in the folder? Do they get overwritten?

**Comment by choisy** [comment]
Good to add these three points in the README I think.

**Comment by thinhong** [comment]
I just tried it and find out it works with relative paths. If your current working directory is the cpp_training, when we run `./DiscreteTimeModel` and the input file is stored in `cpp_training/config/vaccination.json` we can use `config/vaccination.json` for input. We can also type `output` or `test` for the output folder it will create new folder in the current cpp_training folder

**Comment by choisy** [comment]
Great news! OK, can you add these 3 points in the README then?
