### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by choisy** [thinhong/cpp_training#8]
I'm confused by the first 2 transitions shown in the example config JSON file of the README:
```
"S -> 0.3 * I": {"distribution": "mathExpression", "expression": "beta * S * I / N"}, 
"S -> 0.7 * V": {"distribution": "frequency", "frequency": 2},
```
As I understand, whatever is in between the curly braces informs about the distribution of the waiting time in the compartment that is left of the `->` sign right? I that case, I would expect to see exactly the same thing here on these two lines. But then, it would be weird too. So, maybe you should decompose this into 2 other types of lines. One that specifies you getting out of S and another one that specifies where you go once you are out of S.

Other question: what frequency is exactly?

**Comment by choisy** [comment]
Also, I don't understand this sentence in the README:
```
S -> I then S -> V: compartment S transitions to compartment I, then the rest of S transitions to I
```

**Comment by thinhong** [comment]
Yes, omg I just realized how misleading it is when I wrote `p * I1` but not `p * V1`. I will make the two formalisms possible.

**Comment by thinhong** [comment]
I've changed it and also make sure we can write either `p * V1 -> I1` or `V1 * p -> I1` (compartment * percentage or percentage * compartment)
<img width="781" alt="137440439-508a43de-f22a-4ef2-81fe-3baae1235a2f" src="https://user-images.githubusercontent.com/34956551/142377686-53542442-29b6-4b11-b991-cac6732f28f6.png">
About this multinomial, my current algorithm is that when you write `"I -> IA, IM, IS" = {"distribution": "multinomial", "probabilities": [0.1, 0.3, 0.6]}`, if there are 10 people in the I compartment, we directly multiply it i.e 10 * 0.1 = 1 will go to IA, 10 * 0.3 = 3 go to IM and 10 * 0.6 = 6 go to IS. Is that what you mean?
